### ISSUE TITLE
Unable to download.

### ISSUE THREAD

**Issue by LeeJZh** [BayesWatch/cinic-10#2]
> --2019-01-05 11:44:12--  https://datashare.is.ed.ac.uk/bitstream/handle/10283/3192/CINIC-10.tar.gz
> 正在连接 127.0.0.1:46661... 已连接。
> 已发出 Proxy 请求，正在等待回应... 200 OK
> 长度： 0 [application/x-gzip]
> 正在保存至: “CINIC-10.tar.gz”
> 
> CINIC-10.tar.gz         [ <=>                ]       0  --.-KB/s    用时 0s    
> 
> 2019-01-05 11:44:23 (0.00 B/s) - 已保存 “CINIC-10.tar.gz” [0/0])
>

**Comment by learning-luke** [comment]
Is this still a problem? I don't believe it is. Closing.
